site_name: pyzot
site_description: CLI for querying, exporting, and adding to a local Zotero library.
repo_url: https://github.com/CameronBrooks11/pyzot
repo_name: CameronBrooks11/pyzot

theme:
  name: material
  features:
    - navigation.tabs
    - navigation.indexes
    - content.code.copy

plugins:
  - search
  - mkdocstrings:
      default_handler: python
      handlers:
        python:
          paths: [src]
          options:
            show_root_heading: true
            show_source: true

markdown_extensions:
  - mkdocs-click

nav:
  - Home: index.md
  - Getting Started: getting-started.md
  - CLI Reference: cli-reference.md
  - Data Models: data-models.md
  - API Reference: api-reference.md
